services:
  - type: web
    name: journal-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn journal_core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: GEMINI_API_KEY
        sync: false
